import React from "react";
import Head from "next/head";
import Hero from "../components/Hero/hero";
import PageContainer from "../components/Layout/pageContainer";
import {db} from "../lib/firebase"; // Ensure correct import

import {
  collection,
  getDocs,
} from "firebase/firestore";


const landingPage = ({projects, blogPosts}) => {
  return (
    <div className="flex flex-col items-center justify-center bg-gradient-to-br from-white to-gray-500">
      <Head>
        <title>Eason Jiang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <PageContainer>
        <Hero />
      </PageContainer>
    </div>
  );
};

export default landingPage;
